// Generated by Haxe 3.4.1
(function () { "use strict";
function $extend(from, fields) {
	function Inherit() {} Inherit.prototype = from; var proto = new Inherit();
	for (var name in fields) proto[name] = fields[name];
	if( fields.toString !== Object.prototype.toString ) proto.toString = fields.toString;
	return proto;
}
var HxOverrides = function() { };
HxOverrides.iter = function(a) {
	return { cur : 0, arr : a, hasNext : function() {
		return this.cur < this.arr.length;
	}, next : function() {
		return this.arr[this.cur++];
	}};
};
var Lambda = function() { };
Lambda.has = function(it,elt) {
	var x = $iterator(it)();
	while(x.hasNext()) {
		var x1 = x.next();
		if(x1 == elt) {
			return true;
		}
	}
	return false;
};
var Main = function() { };
Main.main = function() {
	$("document").ready(Manager.init);
};
var Manager = function() { };
Manager.init = function(event) {
	utils_Storage.init();
	utils_Message.init();
	utils_EventManager.init();
	view_PageManager.init();
	Manager.onInit();
};
Manager.onInit = function() {
	utils_Storage.get(function(data) {
		view_PageManager.setView(data);
		utils_Message.send("on loaded","nice");
	});
};
var Reflect = function() { };
Reflect.getProperty = function(o,field) {
	var tmp;
	if(o == null) {
		return null;
	} else {
		var tmp1;
		if(o.__properties__) {
			tmp = o.__properties__["get_" + field];
			tmp1 = tmp;
		} else {
			tmp1 = false;
		}
		if(tmp1) {
			return o[tmp]();
		} else {
			return o[field];
		}
	}
};
Reflect.setProperty = function(o,field,value) {
	var tmp;
	var tmp1;
	if(o.__properties__) {
		tmp = o.__properties__["set_" + field];
		tmp1 = tmp;
	} else {
		tmp1 = false;
	}
	if(tmp1) {
		o[tmp](value);
	} else {
		o[field] = value;
	}
};
Reflect.fields = function(o) {
	var a = [];
	if(o != null) {
		var hasOwnProperty = Object.prototype.hasOwnProperty;
		for( var f in o ) {
		if(f != "__id__" && f != "hx__closures__" && hasOwnProperty.call(o,f)) {
			a.push(f);
		}
		}
	}
	return a;
};
var haxe_IMap = function() { };
var haxe_ds_StringMap = function() {
	this.h = { };
};
haxe_ds_StringMap.__interfaces__ = [haxe_IMap];
haxe_ds_StringMap.prototype = {
	setReserved: function(key,value) {
		if(this.rh == null) {
			this.rh = { };
		}
		this.rh["$" + key] = value;
	}
	,getReserved: function(key) {
		if(this.rh == null) {
			return null;
		} else {
			return this.rh["$" + key];
		}
	}
	,keys: function() {
		return HxOverrides.iter(this.arrayKeys());
	}
	,arrayKeys: function() {
		var out = [];
		for( var key in this.h ) {
		if(this.h.hasOwnProperty(key)) {
			out.push(key);
		}
		}
		if(this.rh != null) {
			for( var key in this.rh ) {
			if(key.charCodeAt(0) == 36) {
				out.push(key.substr(1));
			}
			}
		}
		return out;
	}
};
var utils_EventManager = function() { };
utils_EventManager.init = function() {
	utils_EventManager._keys = [];
	utils_EventManager._jWindow.on({ keydown : utils_EventManager.onKeydown, keyup : utils_EventManager.onKeyup});
};
utils_EventManager.onKeydown = function(event) {
	utils_EventManager._keys.push(event.keyCode);
	if(Lambda.has(utils_EventManager._keys,91) && event.keyCode == 13) {
		view_PageManager.onShortcutSave();
	}
};
utils_EventManager.onKeyup = function(event) {
	utils_EventManager._keys = [];
	var _g = event.keyCode;
	if(_g == 13) {
		view_PageManager.onEnterKey();
	}
};
var utils_Message = function() { };
utils_Message.init = function() {
	utils_Message._jParent = $("#message");
};
utils_Message.send = function(message,status) {
	var jText = utils_Message._jParent.empty().append("<p class=\"" + status + "\">" + message + "</p>").find("p");
	jText.css({ top : 5, opacity : 0}).animate({ top : 0, opacity : 1},100,"easeInOutSine",function() {
		jText.delay(1500).animate({ opacity : 0},200,null,function() {
			jText.remove();
		});
	});
};
var utils_Storage = function() { };
utils_Storage.init = function() {
	utils_Storage._storage = chrome.storage.local;
};
utils_Storage.get = function(callback) {
	utils_Storage._storage.get("memomemo",function(object) {
		var data = Reflect.getProperty(object,"memomemo");
		callback(data);
	});
};
utils_Storage.save = function(key,value) {
	utils_Storage.get(function(data) {
		if(data == null) {
			data = { };
		}
		Reflect.setProperty(data,key,value);
		var object = { };
		Reflect.setProperty(object,"memomemo",data);
		utils_Storage._storage.set(object,function() {
			utils_Message.send("Successfully saved \"" + key + "\"","success");
		});
	});
};
var view_Page = function(pagename) {
	this._pagename = pagename;
	this._jParent = $("[data-content=\"" + this._pagename + "\"]");
	this._jParent.find(".button-save").on({ "click" : $bind(this,this.save)});
};
view_Page.prototype = {
	save: function() {
	}
	,set: function(data) {
	}
	,focus: function() {
	}
	,show: function() {
		this._jParent.show().addClass("current");
		this.focus();
	}
	,hide: function() {
		this._jParent.hide().removeClass("current");
	}
	,isCurrent: function() {
		return this._jParent.hasClass("current");
	}
	,getPagename: function() {
		return this._pagename;
	}
	,getJParent: function() {
		return this._jParent;
	}
	,onEnterKey: function() {
	}
	,getData: function(data) {
		return Reflect.getProperty(data,this._pagename);
	}
};
var view_PageManager = function() { };
view_PageManager.init = function() {
	view_PageManager._Pages = new haxe_ds_StringMap();
	var this1 = view_PageManager._Pages;
	var v = new view_page_Memo();
	var _this = this1;
	if(__map_reserved["memo"] != null) {
		_this.setReserved("memo",v);
	} else {
		_this.h["memo"] = v;
	}
	var this2 = view_PageManager._Pages;
	var v1 = new view_page_Setting();
	var _this1 = this2;
	if(__map_reserved["setting"] != null) {
		_this1.setReserved("setting",v1);
	} else {
		_this1.h["setting"] = v1;
	}
	$("[data-jump]").on("click",null,function(event) {
		view_PageManager.hideAll();
		var id = $(event.currentTarget).data("jump");
		var _this2 = view_PageManager._Pages;
		(__map_reserved[id] != null ? _this2.getReserved(id) : _this2.h[id]).show();
	});
};
view_PageManager.setView = function(data) {
	view_PageManager.counter(function(page) {
		page.set(data);
	});
	view_PageManager.hideAll();
	var _this = view_PageManager._Pages;
	(__map_reserved["memo"] != null ? _this.getReserved("memo") : _this.h["memo"]).show();
};
view_PageManager.onShortcutSave = function() {
	view_PageManager.getCurrentPage().save();
};
view_PageManager.onEnterKey = function() {
	view_PageManager.getCurrentPage().onEnterKey();
};
view_PageManager.hideAll = function() {
	view_PageManager.counter(function(page) {
		page.hide();
	});
};
view_PageManager.getCurrentPage = function() {
	var currentPage = null;
	view_PageManager.counter(function(page) {
		if(page.isCurrent()) {
			currentPage = page;
		}
	});
	return currentPage;
};
view_PageManager.counter = function(func) {
	var key = view_PageManager._Pages.keys();
	while(key.hasNext()) {
		var key1 = key.next();
		var _this = view_PageManager._Pages;
		func(__map_reserved[key1] != null ? _this.getReserved(key1) : _this.h[key1]);
	}
};
var view_page_Memo = function() {
	view_Page.call(this,"memo");
	view_page_Memo.jTextarea = $("#textarea");
	view_page_Memo.jTextarea.focus();
};
view_page_Memo.__super__ = view_Page;
view_page_Memo.prototype = $extend(view_Page.prototype,{
	save: function() {
		var value = view_page_Memo.jTextarea.val();
		utils_Storage.save(this._pagename,value);
		this.focus();
	}
	,set: function(data) {
		var value = view_Page.prototype.getData.call(this,data);
		view_page_Memo.jTextarea.val(value);
	}
	,focus: function() {
		view_page_Memo.jTextarea.focus();
	}
});
var view_page_Setting = function() {
	view_Page.call(this,"setting");
	view_page_Setting._jSettingList = this._jParent.find(".setting-list").find("input[type=\"text\"]");
};
view_page_Setting.__super__ = view_Page;
view_page_Setting.prototype = $extend(view_Page.prototype,{
	save: function() {
		var data = this.getListData();
		if(!this.validate(data)) {
			utils_Message.send("Input error","error");
			return;
		}
		this.setStyles(data);
		utils_Storage.save(this._pagename,data);
	}
	,set: function(data) {
		var value = view_Page.prototype.getData.call(this,data);
		this.setStyles(value,function(key,value1) {
			view_page_Setting._jSettingList.filter("[name=\"" + key + "\"]").val(value1);
		});
	}
	,focus: function() {
		this._jParent.find("input:visible").eq(0).focus();
	}
	,onEnterKey: function() {
		var jCur = this._jParent.find(":focus");
		var index = view_page_Setting._jSettingList.index(jCur);
		if(view_page_Setting._jSettingList.length - 1 == index) {
			this._jParent.find(".button-save").focus();
		} else {
			view_page_Setting._jSettingList.eq(index + 1).focus();
		}
	}
	,getListData: function() {
		var data = { };
		var length = view_page_Setting._jSettingList.length;
		var _g1 = 0;
		var _g = length;
		while(_g1 < _g) {
			var i = _g1++;
			var jTarget = view_page_Setting._jSettingList.eq(i);
			var key = jTarget.prop("name");
			var value = jTarget.val();
			data[key] = value;
		}
		return data;
	}
	,setStyles: function(data,insertFunc) {
		var fields = Reflect.fields(data);
		var _g1 = 0;
		var _g = fields.length;
		while(_g1 < _g) {
			var i = _g1++;
			var key = fields[i];
			var value = Reflect.getProperty(data,key);
			this.setStyle(key,value);
			if(insertFunc != null) {
				insertFunc(key,value);
			}
		}
	}
	,setStyle: function(key,value) {
		if(value == "") {
			return;
		}
		switch(key) {
		case "fontSize":
			$("html").css({ fontSize : value + "px"});
			break;
		case "height":
			$(".inputarea").css({ height : value});
			break;
		case "width":
			$("#all").css({ width : value});
			break;
		}
	}
	,validate: function(data) {
		var result = true;
		return result;
	}
});
function $iterator(o) { if( o instanceof Array ) return function() { return HxOverrides.iter(o); }; return typeof(o.iterator) == 'function' ? $bind(o,o.iterator) : o.iterator; }
var $_, $fid = 0;
function $bind(o,m) { if( m == null ) return null; if( m.__id__ == null ) m.__id__ = $fid++; var f; if( o.hx__closures__ == null ) o.hx__closures__ = {}; else f = o.hx__closures__[m.__id__]; if( f == null ) { f = function(){ return f.method.apply(f.scope, arguments); }; f.scope = o; f.method = m; o.hx__closures__[m.__id__] = f; } return f; }
var __map_reserved = {}
Manager.APP_NAME = "memomemo";
utils_EventManager._jWindow = $(window);
Main.main();
})();
